"""Generate ptp4l configuration files from ClusterTimeConfig."""

from __future__ import annotations

import os
from typing import Dict

from .config import ClusterTimeConfig

_CONF_DIR = "/var/run/clustertime"

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_MASTER_CONF = """\
# ptp4l master config - generated by clustertime
[global]
# Use system clock as free-running PTP reference (clockClass 135 = software-only)
network_transport       {transport}
clockClass              135
clockAccuracy           0xFE
offsetScaledLogVariance 0xFFFF
free_running            1
tx_timestamp_timeout    10
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
domainNumber            {domain}
time_stamping           software
twoStepFlag             1
summary_interval        0
# Allow relay nodes to request unicast sync grants
unicast_req_duration    {unicast_req_duration}
uds_address             /var/run/ptp4l_master

[{iface}]
serverOnly              1
# Accept unicast negotiation requests from relay clients.
unicast_listen          1
"""

_RELAY_UPSTREAM_CONF = """\
# ptp4l relay upstream config (unicast slave → master)
# generated by clustertime
[global]
network_transport       {transport}
slaveOnly               1
# Keep relay upstream from winning BMCA if any external master is visible.
priority1               255
priority2               255
# Unicast slave mode: do not use multicast announce/sync service.
inhibit_multicast_service 1
tx_timestamp_timeout    10
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
domainNumber            {domain}
time_stamping           software
twoStepFlag             1
summary_interval        0
# Explicitly request unicast service; some ptp4l builds default this to 0.
unicast_req_duration    {unicast_req_duration}
uds_address             /var/run/ptp4l_upstream

[{iface}]
unicast_master_table    1

[unicast_master_table]
table_id                1
logQueryInterval        2
UDPv4                   {master_ip}
"""

_RELAY_DOWNSTREAM_CONF = """\
# ptp4l relay downstream config (multicast master → local clients)
# generated by clustertime
[global]
# free_running=1: serve system clock (already synced by upstream ptp4l)
network_transport       {transport}
clockClass              135
clockAccuracy           0xFE
offsetScaledLogVariance 0xFFFF
free_running            1
tx_timestamp_timeout    10
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
domainNumber            {domain}
time_stamping           software
twoStepFlag             1
summary_interval        0
uds_address             /var/run/ptp4l_downstream

[{iface}]
serverOnly              1
"""


# ---------------------------------------------------------------------------

def generate_configs(
    cfg: ClusterTimeConfig, conf_dir: str = _CONF_DIR
) -> Dict[str, str]:
    """
    Write ptp4l .conf files and return a dict of role → file path.

    Master mode  → {"master": "/var/run/clustertime/ptp4l_master.conf"}
    Relay mode   → {"upstream": "...", "downstream": "..."}
    """
    os.makedirs(conf_dir, exist_ok=True)
    paths: Dict[str, str] = {}
    p = cfg.ptp

    if cfg.mode == "master":
        content = _MASTER_CONF.format(
            iface=cfg.interface,
            transport=p.transport,
            domain=p.domain,
            sync_interval=p.sync_interval,
            announce_interval=p.announce_interval,
            min_delay_req=p.min_delay_req_interval,
            unicast_req_duration=p.unicast_req_duration,
        )
        path = os.path.join(conf_dir, "ptp4l_master.conf")
        _write(path, content)
        paths["master"] = path

    elif cfg.mode == "relay":
        if cfg.dual_interface:
            up_iface = cfg.upstream_interface
            down_iface = cfg.downstream_interface
        else:
            # Single physical interface: use macvlan sub-interfaces
            # (created by network.py before config is applied)
            up_iface = f"{cfg.interface}.up"
            down_iface = f"{cfg.interface}.down"

        up_content = _RELAY_UPSTREAM_CONF.format(
            iface=up_iface,
            transport=p.transport,
            domain=p.domain,
            sync_interval=p.sync_interval,
            announce_interval=p.announce_interval,
            min_delay_req=p.min_delay_req_interval,
            unicast_req_duration=p.unicast_req_duration,
            master_ip=cfg.master.ip,
        )
        up_path = os.path.join(conf_dir, "ptp4l_upstream.conf")
        _write(up_path, up_content)
        paths["upstream"] = up_path

        down_content = _RELAY_DOWNSTREAM_CONF.format(
            iface=down_iface,
            transport=p.transport,
            domain=p.domain,
            sync_interval=p.sync_interval,
            announce_interval=p.announce_interval,
            min_delay_req=p.min_delay_req_interval,
        )
        down_path = os.path.join(conf_dir, "ptp4l_downstream.conf")
        _write(down_path, down_content)
        paths["downstream"] = down_path

    return paths


def _write(path: str, content: str) -> None:
    with open(path, "w") as fh:
        fh.write(content)
