"""Generate ptp4l configuration files from ClusterTimeConfig."""

from __future__ import annotations

import logging
import os
import pathlib
import shutil
import subprocess
from typing import Dict

from .config import ClusterTimeConfig

_CONF_DIR = "/var/run/clustertime"
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_MASTER_CONF = """\
# ptp4l master config - generated by clustertime
[global]
# Use system clock as free-running PTP reference (clockClass 135 = software-only)
network_transport       {transport}
priority1               {master_priority1}
priority2               {master_priority2}
clockClass              135
clockAccuracy           0xFE
offsetScaledLogVariance 0xFFFF
free_running            1
tx_timestamp_timeout    {tx_timestamp_timeout}
# Controls IPv4 TTL / IPv6 hop-limit for outgoing UDP PTP packets.
udp_ttl                 {udp_ttl}
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
domainNumber            {domain}
ptp_minor_version       {minor_version}
time_stamping           {time_stamping}
twoStepFlag             1
summary_interval        0
# In unicast deployments, send Delay_Req to the current master via unicast.
hybrid_e2e              1
# Allow relay nodes to request unicast sync grants
unicast_req_duration    {unicast_req_duration}
uds_address             /var/run/ptp4l_master

{interface_blocks}
"""

_RELAY_UPSTREAM_CONF = """\
# ptp4l relay upstream config (unicast slave → master)
# generated by clustertime
[global]
network_transport       {transport}
clientOnly              1
# Keep relay upstream from winning BMCA if any external master is visible.
priority1               {relay_priority1}
priority2               {relay_priority2}
# Unicast slave mode: do not use multicast announce/sync service.
inhibit_multicast_service 1
tx_timestamp_timeout    {tx_timestamp_timeout}
# Controls IPv4 TTL / IPv6 hop-limit for outgoing UDP PTP packets.
udp_ttl                 {udp_ttl}
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
announceReceiptTimeout  {announce_receipt_timeout}
domainNumber            {domain}
ptp_minor_version       {minor_version}
time_stamping           {time_stamping}
twoStepFlag             1
summary_interval        0
# In unicast deployments, send Delay_Req to the current master via unicast.
hybrid_e2e              1
# Explicitly request unicast service; some ptp4l builds default this to 0.
unicast_req_duration    {unicast_req_duration}
uds_address             /var/run/ptp4l_upstream

[{iface}]
unicast_master_table    1

[unicast_master_table]
# linuxptp expects a generic unicast_master_table section with table_id set
# inside the block (not in the section header).
table_id                1
# Keep the table entry minimal for compatibility with older linuxptp builds.
UDPv4                   {master_ip}
"""

_RELAY_DOWNSTREAM_CONF = """\
# ptp4l relay downstream config (multicast master → local clients)
# generated by clustertime
[global]
# free_running=1: serve system clock (already synced by upstream ptp4l)
network_transport       {transport}
priority1               {relay_priority1}
priority2               {relay_priority2}
clockClass              135
clockAccuracy           0xFE
offsetScaledLogVariance 0xFFFF
free_running            1
tx_timestamp_timeout    {tx_timestamp_timeout}
# Controls IPv4 TTL / IPv6 hop-limit for outgoing UDP PTP packets.
udp_ttl                 {udp_ttl}
logMinDelayReqInterval  {min_delay_req}
logSyncInterval         {sync_interval}
logAnnounceInterval     {announce_interval}
domainNumber            {domain}
ptp_minor_version       {minor_version}
time_stamping           {time_stamping}
twoStepFlag             1
summary_interval        0
{clock_identity_line}uds_address             {uds_address}

[{iface}]
serverOnly              1
# Allow downstream clients (including tiered relays) to request unicast grants.
unicast_listen          1
"""


# ---------------------------------------------------------------------------

def generate_configs(
    cfg: ClusterTimeConfig, conf_dir: str = _CONF_DIR
) -> Dict[str, str]:
    """
    Write ptp4l .conf files and return a dict of role → file path.

    Master mode  → {"master": "/var/run/clustertime/ptp4l_master.conf"}
    Relay mode   → {"upstream": "...", "downstream:<iface>": "..."}
    """
    os.makedirs(conf_dir, exist_ok=True)
    paths: Dict[str, str] = {}
    p = cfg.ptp

    if cfg.mode == "master":
        bind_ifaces = cfg.master_bind_interfaces
        interface_blocks = "\n".join(
            [
                "\n".join(
                    [
                        f"[{iface}]",
                        "serverOnly              1",
                        "inhibit_multicast_service "
                        + (
                            "1"
                            if cfg.master_inhibit_multicast_service.get(iface, False)
                            else "0"
                        ),
                        "# Accept unicast negotiation requests from relay clients.",
                        "unicast_listen          1",
                    ]
                )
                for iface in bind_ifaces
            ]
        )
        content = _MASTER_CONF.format(
            transport=p.transport,
            master_priority1=p.master_priority1,
            master_priority2=p.master_priority2,
            domain=p.domain,
            sync_interval=p.sync_interval,
            minor_version=p.minor_version,
            announce_interval=p.announce_interval,
            min_delay_req=p.min_delay_req_interval,
            unicast_req_duration=p.unicast_req_duration,
            time_stamping=_master_time_stamping_for_iface(cfg, bind_ifaces[0]),
            tx_timestamp_timeout=p.tx_timestamp_timeout,
            udp_ttl=p.multicast_ttl,
            interface_blocks=interface_blocks,
        )
        path = os.path.join(conf_dir, "ptp4l_master.conf")
        _write(path, content)
        paths["master"] = path

    elif cfg.mode == "relay":
        if cfg.dual_interface:
            up_iface = cfg.upstream_interface
            down_ifaces = cfg.downstream_interfaces
        else:
            # Single physical interface: use macvlan sub-interfaces
            # (created by network.py before config is applied)
            up_iface = f"{cfg.interface}.up"
            down_ifaces = [f"{cfg.interface}.down"]

        up_content = _RELAY_UPSTREAM_CONF.format(
            iface=up_iface,
            transport=p.transport,
            relay_priority1=p.relay_priority1,
            relay_priority2=p.relay_priority2,
            domain=p.domain,
            sync_interval=p.sync_interval,
            minor_version=p.minor_version,
            announce_interval=p.announce_interval,
            announce_receipt_timeout=p.announce_receipt_timeout,
            min_delay_req=p.min_delay_req_interval,
            unicast_req_duration=p.unicast_req_duration,
            master_ip=cfg.master.ip,
            time_stamping=_relay_time_stamping_for_iface(cfg, up_iface, role="upstream"),
            tx_timestamp_timeout=p.tx_timestamp_timeout,
            udp_ttl=p.unicast_ttl,
        )
        up_path = os.path.join(conf_dir, "ptp4l_upstream.conf")
        _write(up_path, up_content)
        paths["upstream"] = up_path

        for idx, down_iface in enumerate(down_ifaces):
            down_content = _RELAY_DOWNSTREAM_CONF.format(
                iface=down_iface,
                transport=p.transport,
                relay_priority1=p.relay_priority1,
                relay_priority2=p.relay_priority2,
                domain=p.domain,
                sync_interval=p.sync_interval,
                minor_version=p.minor_version,
                announce_interval=p.announce_interval,
                min_delay_req=p.min_delay_req_interval,
                time_stamping=_relay_time_stamping_for_iface(cfg, down_iface, role="downstream"),
                tx_timestamp_timeout=p.tx_timestamp_timeout,
                udp_ttl=p.multicast_ttl,
                clock_identity_line=_clock_identity_line(p.downstream_clock_identity),
                uds_address=_downstream_uds_address(idx),
            )
            suffix = f"_{idx}" if idx else ""
            down_path = os.path.join(conf_dir, f"ptp4l_downstream{suffix}.conf")
            _write(down_path, down_content)
            paths[f"downstream:{down_iface}"] = down_path

    return paths


def _write(path: str, content: str) -> None:
    with open(path, "w") as fh:
        fh.write(content)


def _resolve_time_stamping(mode: str, iface: str) -> str:
    """
    Resolve effective ptp4l time_stamping setting for an interface.

    mode:
      - software: always software
      - hardware: always hardware
      - auto: use hardware when capability is detected, else software
    """
    normalized = mode.strip().lower()
    if normalized in ("software", "hardware"):
        return normalized
    if normalized != "auto":
        # config.validate should prevent this; keep a safe fallback.
        log.warning("Unknown time_stamping mode %r, defaulting to software", mode)
        return "software"
    if _supports_hardware_timestamping(iface):
        log.info("Interface %s supports hardware timestamping; using hardware", iface)
        return "hardware"
    log.info("Interface %s does not expose hardware timestamping; using software", iface)
    return "software"


def _relay_time_stamping_for_iface(cfg: ClusterTimeConfig, iface: str, role: str) -> str:
    """
    Resolve per-interface timestamping mode for relay roles.

    Optional Raspberry Pi hybrid mode forces upstream to software timestamping
    (to avoid missing RX timestamps) while leaving downstream behavior unchanged.
    """
    if cfg.ptp.rpi_hybrid_ts and role == "upstream" and _is_raspberry_pi():
        log.warning(
            "Raspberry Pi hybrid timestamping enabled: forcing upstream interface %s "
            "to software timestamping",
            iface,
        )
        return "software"
    return _resolve_time_stamping(cfg.ptp.time_stamping, iface)


def _master_time_stamping_for_iface(cfg: ClusterTimeConfig, iface: str) -> str:
    """
    Resolve timestamping mode for master role.

    Optional Raspberry Pi hybrid mode forces master to software timestamping
    on Raspberry Pi devices.
    """
    if cfg.ptp.rpi_hybrid_ts and _is_raspberry_pi():
        log.warning(
            "Raspberry Pi hybrid timestamping enabled: forcing master interface %s "
            "to software timestamping",
            iface,
        )
        return "software"
    return _resolve_time_stamping(cfg.ptp.time_stamping, iface)

def _downstream_uds_address(index: int) -> str:
    suffix = f"_{index}" if index else ""
    return f"/var/run/ptp4l_downstream{suffix}"


def _clock_identity_line(identity: str | None) -> str:
    if not identity:
        return ""
    normalized = _normalize_clock_identity(identity)
    return f"clockIdentity           {normalized}\n"


def _normalize_clock_identity(identity: str) -> str:
    """
    Normalize clock identity into linuxptp textual format.

    linuxptp expects an 8-octet identity as 6-4-6 hex groups:
    e.g. 001122.3344.556677.
    """
    raw = identity.strip()
    # Accept common forms:
    # - aa:bb:cc:dd:ee:ff:00:11
    # - aabbccddeeff0011
    # - aabbcc.ddee.ff0011
    compact = raw.replace(":", "").replace(".", "")
    if len(compact) != 16:
        return raw
    try:
        int(compact, 16)
    except ValueError:
        return raw
    compact = compact.lower()
    return f"{compact[:6]}.{compact[6:10]}.{compact[10:]}"


def _is_raspberry_pi() -> bool:
    model_file = pathlib.Path("/proc/device-tree/model")
    try:
        if model_file.exists():
            model = model_file.read_text(errors="ignore").lower()
            return "raspberry pi" in model
    except Exception:  # pragma: no cover - defensive probe path
        return False
    return False


def _supports_hardware_timestamping(iface: str) -> bool:
    """
    Best-effort interface capability probe.

    Prefers ethtool -T output, with a sysfs fallback for NIC-backed PTP clocks.
    """
    ethtool = shutil.which("ethtool")
    if ethtool:
        try:
            result = subprocess.run(
                [ethtool, "-T", iface],
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode == 0:
                out = result.stdout.lower()
                hw_tokens = ("hardware-transmit", "hardware-receive", "hardware-raw-clock")
                if any(tok in out for tok in hw_tokens):
                    return True
        except Exception as exc:  # pragma: no cover - defensive probe path
            log.debug("ethtool probe failed for %s: %s", iface, exc)

    # Fallback: NIC has an associated PHC device in sysfs.
    ptp_link = pathlib.Path("/sys/class/net") / iface / "device" / "ptp"
    try:
        if ptp_link.exists():
            return True
    except Exception:  # pragma: no cover - defensive probe path
        return False
    return False
